import { AlgorithmEntity } from '../../types/algorithm';

export type AlgorithmSeedItem = Omit<AlgorithmEntity, 'created_at' | 'updated_at'>;

export const ALGORITHM_SEEDS: AlgorithmSeedItem[] = [
  {
    id: 'bubble_sort',
    name: 'Bubble Sort',
    category: 'sorting',
    display_order: 1,
    input_type: 'array',
    time_complexity_best: 'O(n)',
    time_complexity_avg: 'O(n²)',
    time_complexity_worst: 'O(n²)',
    space_complexity: 'O(1)',
    description:
      'Iteratively compares adjacent elements and swaps them if out of order, bubbling the largest elements to the end.',
    is_enabled: 1,
  },
  {
    id: 'selection_sort',
    name: 'Selection Sort',
    category: 'sorting',
    display_order: 2,
    input_type: 'array',
    time_complexity_best: 'O(n²)',
    time_complexity_avg: 'O(n²)',
    time_complexity_worst: 'O(n²)',
    space_complexity: 'O(1)',
    description:
      'Divides the list into sorted and unsorted regions, repeatedly finding the minimum element from the unsorted region and moving it to the front.',
    is_enabled: 1,
  },
  {
    id: 'insertion_sort',
    name: 'Insertion Sort',
    category: 'sorting',
    display_order: 3,
    input_type: 'array',
    time_complexity_best: 'O(n)',
    time_complexity_avg: 'O(n²)',
    time_complexity_worst: 'O(n²)',
    space_complexity: 'O(1)',
    description:
      'Builds the final sorted array one element at a time by sequentially inserting each element into its proper position.',
    is_enabled: 1,
  },
  {
    id: 'merge_sort',
    name: 'Merge Sort',
    category: 'sorting',
    display_order: 4,
    input_type: 'array',
    time_complexity_best: 'O(n log n)',
    time_complexity_avg: 'O(n log n)',
    time_complexity_worst: 'O(n log n)',
    space_complexity: 'O(n)',
    description:
      'Divide-and-conquer algorithm that recursively splits the array in halves, sorts them, and merges the sorted subarrays.',
    is_enabled: 1,
  },
  {
    id: 'quick_sort',
    name: 'Quick Sort',
    category: 'sorting',
    display_order: 5,
    input_type: 'array',
    time_complexity_best: 'O(n log n)',
    time_complexity_avg: 'O(n log n)',
    time_complexity_worst: 'O(n²)',
    space_complexity: 'O(log n)',
    description:
      'Divide-and-conquer algorithm that partitions the array around a pivot element using Lomuto partitioning and recursively sorts the sub-partitions.',
    is_enabled: 1,
  },
  {
    id: 'linear_search',
    name: 'Linear Search',
    category: 'searching',
    display_order: 6,
    input_type: 'array_and_target',
    time_complexity_best: 'O(1)',
    time_complexity_avg: 'O(n)',
    time_complexity_worst: 'O(n)',
    space_complexity: 'O(1)',
    description:
      'Sequentially checks each element of the list until a match is found or the whole list has been searched.',
    is_enabled: 1,
  },
  {
    id: 'binary_search',
    name: 'Binary Search',
    category: 'searching',
    display_order: 7,
    input_type: 'array_and_target',
    time_complexity_best: 'O(1)',
    time_complexity_avg: 'O(log n)',
    time_complexity_worst: 'O(log n)',
    space_complexity: 'O(1)',
    description:
      'Efficiently locates a target value within a sorted array by repeatedly dividing the search interval in half.',
    is_enabled: 1,
  },
  {
    id: 'stack',
    name: 'Stack',
    category: 'data_structures',
    display_order: 8,
    input_type: 'data_structure_ops',
    time_complexity_best: 'O(1)',
    time_complexity_avg: 'O(1)',
    time_complexity_worst: 'O(1)',
    space_complexity: 'O(n)',
    description:
      'Linear data structure following the Last-In-First-Out (LIFO) principle with fixed-capacity array backing.',
    is_enabled: 1,
  },
  {
    id: 'queue',
    name: 'Queue',
    category: 'data_structures',
    display_order: 9,
    input_type: 'data_structure_ops',
    time_complexity_best: 'O(1)',
    time_complexity_avg: 'O(1)',
    time_complexity_worst: 'O(1)',
    space_complexity: 'O(n)',
    description:
      'Linear data structure following the First-In-First-Out (FIFO) principle, implemented using a singly-linked node chain with head (front) and tail (rear) pointers.',
    is_enabled: 1,
  },
  {
    id: 'linked_list',
    name: 'Singly Linked List',
    category: 'data_structures',
    display_order: 10,
    input_type: 'data_structure_ops',
    time_complexity_best: 'O(1)',
    time_complexity_avg: 'O(n)',
    time_complexity_worst: 'O(n)',
    space_complexity: 'O(n)',
    description:
      'Linear collection of node structures connected by unidirectional pointers supporting dynamic insertions and deletions.',
    is_enabled: 1,
  },
  {
    id: 'binary_tree',
    name: 'Binary Tree',
    category: 'trees',
    display_order: 11,
    input_type: 'tree_preorder',
    time_complexity_best: 'O(n)',
    time_complexity_avg: 'O(n)',
    time_complexity_worst: 'O(n)',
    space_complexity: 'O(w) / O(h)',
    description:
      'Hierarchical node structure where each node has at most two children, supporting recursive preorder, inorder, postorder, and level-order traversals.',
    is_enabled: 1,
  },
  {
    id: 'bst',
    name: 'Binary Search Tree',
    category: 'trees',
    display_order: 12,
    input_type: 'bst_values',
    time_complexity_best: 'O(log n)',
    time_complexity_avg: 'O(log n)',
    time_complexity_worst: 'O(n)',
    space_complexity: 'O(h)',
    description:
      'Node-based binary tree data structure with the binary search property: left subtree values are strictly less, and right subtree values are strictly greater.',
    is_enabled: 1,
  },
  {
    id: 'bfs',
    name: 'Breadth-First Search',
    category: 'graphs',
    display_order: 13,
    input_type: 'graph_edges',
    time_complexity_best: 'O(V + E)',
    time_complexity_avg: 'O(V + E)',
    time_complexity_worst: 'O(V + E)',
    space_complexity: 'O(V)',
    description:
      'Graph traversal algorithm exploring all neighbor vertices at the present depth level before moving on to vertices at the next depth level using a queue.',
    is_enabled: 1,
  },
  {
    id: 'dfs',
    name: 'Depth-First Search',
    category: 'graphs',
    display_order: 14,
    input_type: 'graph_edges',
    time_complexity_best: 'O(V + E)',
    time_complexity_avg: 'O(V + E)',
    time_complexity_worst: 'O(V + E)',
    space_complexity: 'O(V)',
    description:
      'Graph traversal algorithm exploring as deep as possible along each branch before backtracking using recursive call stack state.',
    is_enabled: 1,
  },
];
